# Generated by Django 2.0.6 on 2018-06-19 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
